image: node:latest

cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm ci
    - npm run build
    - npm run test
    - dpl --provider=heroku --app=kyle-social-media --api-key=$HEROKU_API_KEY
