image: node:latest

cache:
  paths:
    - node_modules/

stages: 
  - staging
  - production

deploy-stage:
  stage: staging
  image: ruby:latest
  script:
    - npm ci
    - npm run build
    - npm run test
    - gem install dpl
    - dpl --provider=heroku --app=stg-kyle-social-media --api-key=$HEROKU_API_KEY --skip-cleanup
  only:
    - master
    
deploy-prod:
  stage: production
  script:
    - npm ci
    - npm run build
    - npm run test
    - dpl --provider=heroku --app=kyle-social-media --api-key=$HEROKU_API_KEY --skip-cleanup
