image: node:latest

cache:
  paths:
    - node_modules/

stages: 
  - .pre
  - staging
  - production

build:
  stage: .pre
  script:
    - npm ci
    - npm run build
    - npm run test
  
deploy-stage:
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=kyle-social-media-stg --api-key=$HEROKU_API_KEY --skip-cleanup
  only:
    - master
    
deploy-prod:
  stage: production
  script:
    - npm ci
    - npm run build
    - npm run test
    - dpl --provider=heroku --app=kyle-social-media --api-key=$HEROKU_API_KEY --skip-cleanup
